# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
PackageIdentifier: harshmendhe-arch.dhriti
PackageVersion: 0.1.4
Platform:
  - Windows.Desktop
InstallerType: zip
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/harshmendhe-arch/dhriti/releases/download/0.1.4/dhriti-windows-x86_64.zip
    InstallerSha256: 01B4563DE141C3E6919FF0D3E84ED64E5FE4FC8F1763413B35FB6146C3B59585
    NestedInstallerType: portable
    NestedInstallerFiles:
      - RelativeFilePath: dhriti.exe
        PortableCommandAlias: dhriti
  - Architecture: arm64
    InstallerUrl: https://github.com/harshmendhe-arch/dhriti/releases/download/0.1.4/dhriti-windows-arm64.zip
    InstallerSha256: 6D5A80C1FABFB08D5233A854340C49003EDD684CE49435352580652A5541BDF4
    NestedInstallerType: portable
    NestedInstallerFiles:
      - RelativeFilePath: dhriti.exe
        PortableCommandAlias: dhriti
ManifestType: installer
ManifestVersion: 1.12.0
